meta_product_name: "TrekğŸ“"
meta_title: "TrekğŸ“ - Plan the Perfect Route"
meta_description: "Explore the great outdoors with Trek, the app that allows you to plan you're hiking adventures."
meta_image: "cover.png"